[build]
  # Comando de construcción
  command = "npm run build"
  
  # Directorio de salida después del build
  publish = "dist"
  
  # Variables de entorno para el build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Configuración de redirecciones para SPA (Single Page Application)
# Esto redirige todas las rutas a index.html para que React Router maneje el enrutamiento
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad y optimización
[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache para assets estáticos
    Cache-Control = "public, max-age=31536000, immutable"

# Headers específicos para HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers para archivos CSS y JS
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración de Forms (si necesitas formularios en el futuro)
# [build]
#   functions = "netlify/functions"

# Configuración de desarrollo local
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Configuración de redirects adicionales para APIs externas (si las necesitas)
# [[redirects]]
#   from = "/api/*"
#   to = "https://tu-api-externa.com/:splat"
#   status = 200
#   force = true

# Plugin para optimización automática (opcional)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

# Configuración de prevención de errores comunes
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
